#!/bin/bash


#simple base inputs validation
if [ -z ${2+x} ]; then
  echo "-i parameter is not set";
  exit 1;
elif [ -z ${4+x} ]; then
  echo "-n parameter is not set";
  exit 1;
elif [ -z ${5+x} ]; then
  echo "command parameter is not set";
  exit 1;
fi

#defining parameters
TIME=$2
LOOPS=$4
COMMAND=${@:5}


#running command and passing errors to stderr
$COMMAND 2>/dev/null


if [ $? -eq 0 ]; then
    echo "Running COMMAND : $COMMAND was  $(tput setab 2)successfully$(tput sgr 0)"
    exit 0;
else
  echo "Running COMMAND : $COMMAND was  $(tput setab 1)failed$(tput sgr 0)"
  for (( i = 1; i <= $LOOPS; i++ )); do
    echo "trying to running again command (LOOP $i)"
    $COMMAND 2>$(pwd)/response.txt
    if [ $? -eq 0 ]; then
      echo "running command in trying loop $i was $(tput setab 2)successfully$(tput sgr 0)";
      exit 0;
    elif [ $i -ne $LOOPS ]; then
      sleep $TIME
    elif [ $i -eq $LOOPS -a $? -ne 0 ]; then
        >&2 echo "$(tput setab 1)error$(tput sgr 0)"
        exit 1;
    fi
  done
fi

exit;
